name: Validate Commit Messages

on:
  pull_request:
    branches:
      - main  # Target branch for pull requests

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures full history to get all commits

      - name: Validate each commit message
        run: |
          # Define the required pattern for commit messages
          PATTERN='AB#'

          # Get all commit messages in the pull request
          COMMITS=$(git log --pretty=format:"%s" origin/main..HEAD)

          echo "Checking the following commit messages:"
          echo "$COMMITS"

          # Loop through each commit message and check if it contains "AB#"
          for COMMIT_MESSAGE in $COMMITS; do
            echo "Checking commit message: $COMMIT_MESSAGE"
            if [[ ! $COMMIT_MESSAGE =~ $PATTERN ]]; then
              echo "Invalid commit message: $COMMIT_MESSAGE. Each commit message must contain 'AB#'."
              exit 1
            fi
          done
        shell: bash
