name: Validate Commit Message

on:
  pull_request:
    branches:
      - main  # Target branch for pull requests

jobs:
  validate-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Fetch only the latest commit

      - name: Validate latest commit message
        run: |
          # Define the required pattern for commit messages
          PATTERN='AB#'

          # Get the latest commit message
          LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")

          echo "Checking latest commit message: $LATEST_COMMIT_MESSAGE"

          # Check if the latest commit message contains "AB#"
          if [[ ! $LATEST_COMMIT_MESSAGE =~ $PATTERN ]]; then
            echo "Invalid commit message: $LATEST_COMMIT_MESSAGE. The commit message must contain 'AB#'."
            exit 1
          fi
        shell: bash
