name: Validate Commit Messages

on:
  pull_request:
    branches:
      - main  # Target branch for pull requests

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history to get all commits in the PR

      - name: Validate each commit message
        run: |
          # Define the required pattern
          PATTERN='^AB#'

          # Get all commit messages in the pull request
          COMMITS=$(git log --pretty=format:"%s" origin/main..HEAD)

          # Loop through each commit message and check if it matches the pattern
          for COMMIT_MESSAGE in $COMMITS; do
            if [[ ! $COMMIT_MESSAGE =~ $PATTERN ]]; then
              echo "Invalid commit message: $COMMIT_MESSAGE. Each commit message must start with 'AB#'."
              exit 1
            fi
          done
        shell: bash
