name: Commit Message Validation

on:
  pull_request:
    branches:
      - main  # Replace with the branch you want to enforce the rule on

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate commit messages
        run: |
          # Define the required pattern for commit messages
          COMMIT_PATTERN='^AB#'

          # Fetch all commits in the pull request
          COMMITS=$(git log --format=%s ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

          # Loop through each commit message and validate
          for COMMIT_MSG in $COMMITS; do
            if [[ ! $COMMIT_MSG =~ $COMMIT_PATTERN ]]; then
              echo "Invalid commit message: $COMMIT_MSG. Each commit message must start with 'AB#'."
              exit 1
            fi
          done
          echo "All commit messages are valid."
        shell: bash
